### ISSUE TITLE
V1alphaDAGTask incorrectly requires template when templateRef is used

### ISSUE THREAD

**Issue by process0** [argoproj-labs/argo-client-python#25]
The `V1alphaDAGTask` incorrectly requires the `template` field when the `templateRef` field is used.  This prevents a `@task` function in `argo-python-dsl` from returning a `V1alpha1TemplateRef` object to generate valid template references.

See: https://argoproj.github.io/argo/workflow-templates/#referencing-other-workflowtemplates

```

Traceback (most recent call last):
  File "test_workflowtemplate_reference.py", line 52, in <module>
    wf = Child()
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 236, in __init__
    self.compile()
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 381, in compile
    self.spec = _compile(self.spec)
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 376, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 373, in _compile
    return list(map(_compile, obj))
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 376, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 376, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 373, in _compile
    return list(map(_compile, obj))
  File "test/argo-python-dsl/argo/workflows/dsl/_workflow.py", line 371, in _compile
    return obj.__get__(self).__call__(**args)
  File "test/argo-python-dsl/argo/workflows/dsl/_base.py", line 64, in __call__
    model: T = spec.__model__(**attr_dict)
  File "test/argo-python-dsl/venv/lib/python3.7/site-packages/argo/workflows/client/models/v1alpha1_dag_task.py", line 96, in __init__
    self.template = template
  File "test/argo-python-dsl/venv/lib/python3.7/site-packages/argo/workflows/client/models/v1alpha1_dag_task.py", line 265, in template
    raise ValueError("Invalid value for `template`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `template`, must not be `None`
```

**Comment by binarycrayon** [comment]
Will take a look, argo-python-dsl probably should add a default value `None` for template

**Comment by process0** [comment]
This occurs with just the `argo-client-python` module too, so i believe the actual issue is in this package.

**Comment by process0** [comment]
Upgraded to 5.0 and stopped seeing this issue.
