### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by yogeshVU** [argoproj-labs/argo-client-python#38]
Hi all,

I am trying to setup and use the python client.. However I get connection error issues. I am trying out the example from the readme.md file.
Here is the log.
```
/argotest/venv/bin/python /argotest/argo_test.py
Traceback (most recent call last):
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1337, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/argotest/argo_test.py", line 18, in <module>
    service.create_workflow('argo', V1alpha1WorkflowCreateRequest(workflow=manifest))
  File "/argotest/venv/lib/python3.8/site-packages/argo/workflows/client/api/workflow_service_api.py", line 62, in create_workflow
    return self.create_workflow_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/argotest/venv/lib/python3.8/site-packages/argo/workflows/client/api/workflow_service_api.py", line 148, in create_workflow_with_http_info
    return self.api_client.call_api(
  File "/argotest/venv/lib/python3.8/site-packages/argo/workflows/client/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/argotest/venv/lib/python3.8/site-packages/argo/workflows/client/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/argotest/venv/lib/python3.8/site-packages/argo/workflows/client/api_client.py", line 407, in request
    return self.rest_client.POST(url,
  File "/argotest/venv/lib/python3.8/site-packages/argo/workflows/client/rest.py", line 265, in POST
    return self.request("POST", url,
  File "/argotest/venv/lib/python3.8/site-packages/argo/workflows/client/rest.py", line 163, in request
    r = self.pool_manager.request(
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/argotest/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1337, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Process finished with exit code 1


```

**Comment by samirmajen** [comment]
i get the same issue - any solution to this ?

**Comment by chrisk314** [comment]
Same problem here. 

Ubuntu 20.04
Python 3.7.12
argo-workflows 5.0.0
